### ISSUE TITLE
Triggers sometimes don't trigger

### ISSUE THREAD

**Issue by SaltySnail** [SaltySnail/Sumo-BeamMP#1]
figure this out

**Comment by iPwnEverything** [comment]
Are you talking to yourself sir? Just kidding - I am interested in these game modes you are making dude - very cool  could we chat sometime ? @SaltySnail 

Just wanted to learn a little more mainly and help out of possible lol - Sounds fun

**Comment by SaltySnail** [comment]
@iPwnEverything I'm down for that, hit me up on my discord; julianstap

**Comment by SaltySnail** [comment]
Whoopsie, didn't mean to close

**Comment by SaltySnail** [comment]
Fixed with commit: [63b092989fe98d2cf4972f89ce345d79c8bbed72](https://github.com/SaltySnail/Sumo-BeamMP/commit/63b092989fe98d2cf4972f89ce345d79c8bbed72)
